=== HamzaNGADI/javaEcore/javatoxml/cmt.dtd
<!ELEMENT banque (compte*)>
<!ELEMENT compte (numCompte, solde)>
<!ELEMENT numCompte (nume,naC)>
<!ELEMENT nume (cm)>
<!ATTLIST compte idCompte CDATA #REQUIRED>
<!ATTLIST numCompte idcheck CDATA #IMPLIED>

<!ELEMENT cm (#PCDATA)>
<!ELEMENT naC (#PCDATA)>
<!ELEMENT solde (#PCDATA)>

=== HamzaNGADI/javaEcore/javatoxml/compte.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE banque SYSTEM "cmt.dtd">


<banque>
  <compte idCompte="1">
    <numCompte idcheck="1">
      <nume>
          <cm>1</cm>
      </nume>
      <naC>1cv</naC>
    </numCompte>
    <solde>2000</solde>
  </compte>
  <compte idCompte="2">
    <numCompte idcheck="1">
      <nume>
        <cm>2</cm>
      </nume>
      <naC>2cv</naC>
    </numCompte>
    <solde>2020</solde>
  </compte>
  <compte idCompte="3">
    <numCompte idcheck="1">
      <nume>
        <cm>3</cm>
      </nume>
      <naC>3cv</naC>
    </numCompte>
    <solde>2040</solde>
  </compte>
</banque>
